HAI 1.2
	CAN HAS STDIO?
	BTW THIS IS A COMMENT
	I HAS A ANSWER
	
	IM IN YR LOOP 
		I HAS A WORD
		VISIBLE ":)IZ CAN HAZ TRANZLAET?"
		GIMMEH WORD
		
		VISIBLE "IZ DUN KNOE HOW 2 TRANZLAET "!
		VISIBLE WORD
	IM OUTTA YR LOOP
	
	BTW SMOOSH...MKAY
KTHXBYE

